# TODO tests are not yet completed
version: 2.1

orbs:
  cypress: cypress-io/cypress@3

jobs:
  e2e-tests:
    docker:
      - image: node:latest

    steps:
      - checkout

      - run:
          name: update apt
          command: apt-get update

      - run:
          name: install system deps
          command: apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - run:
          name: Install deps
          command: cd ./app && npm install

      - cypress/run-tests:
          start-command: npm run dev
          cypress-command: "npx wait-on@latest http://localhost:3000 && npx cypress run"
          working-directory: ./app

      - store_artifacts:
          path: ./app/cypress/screenshots
          when: on_fail

  publish-to-main-branch:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: "SHA256:h3dWritaS+YZEvEuRDqLwqoyX+gA4PwvAhDh+aFmofw"

      - run:
          name: Push to production branch
          command: git push origin main-test-branch:main

  deploy-to-vercel:
    docker:
      - image: node:latest
        environment:
          VERCEL_ORG_ID: $VERCEL_ORG_ID
          VERCEL_PASSWORD_ID: $VERCEL_PASSWORD_ID
    steps:
      - checkout

      - run:
          name: Install vercel
          command: npm i -g vercel@latest

      - run:
          name: PULL VERCEL ENVIRONMENT
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - run:
          name: BUILD PROJECT
          command: vercel build --prod --token=$VERCEL_TOKEN

      - run:
          name: DEPLOY PROJECT
          command: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

workflows:
  the-great-gatsby:
    jobs:
      - e2e-tests:
          filters:
            branches:
              only:
                - main-test-branch

      - publish-to-main-branch:
          requires:
            - e2e-tests

      - deploy-to-vercel:
          requires:
            - e2e-tests
            - publish-to-main-branch
